apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

