name: Create EC2

on:
  workflow_dispatch:  # Manual trigger

jobs:
  create_ec2:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js (Install Node.js)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Ensure working directory points to where the Terraform files are
      - name: Navigate to Terraform configuration
        working-directory: terraform/ec2
        run: pwd  # Verifies we're in the right directory

      - name: Terraform Init (S3 Backend)
        working-directory: terraform/ec2
        run: |
          terraform init -backend-config="bucket=terraform-test-ec2-s3-state" \
                         -backend-config="key=terraform/ec2/state.tfstate" \
                         -backend-config="region=eu-central-1" \
                         -backend-config="encrypt=true"

      - name: Terraform Plan
        working-directory: terraform/ec2
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform/ec2
        run: terraform apply -auto-approve

