name: Create EC2 and S3

on:
  workflow_dispatch:  # Manual trigger

jobs:
  create_ec2_s3:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js (Install Node.js)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Navigate to Terraform configuration
        working-directory: terraform/ec2
        run: pwd  # Verifies we're in the right directory

      - name: Terraform Init (Local State)
        working-directory: terraform/ec2
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/ec2
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform/ec2
        run: terraform apply -auto-approve

