name: Destroy EC2 and S3

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js (Install Node.js)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Step 1: Initialize Terraform and destroy EC2 instance
      - name: Terraform Init and Destroy EC2
        working-directory: terraform/ec2
        run: |
          terraform init -backend-config="bucket=terraform-remote-state-ec2-test" \
                         -backend-config="key=terraform/ec2/state.tfstate" \
                         -backend-config="region=eu-central-1" \
                         -backend-config="encrypt=true"
          terraform destroy -auto-approve
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 2: Empty the S3 Bucket
      - name: Empty S3 Bucket
        run: |
          aws s3 rm s3://terraform-remote-state-ec2-test --recursive
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 3: Delete S3 Bucket
      - name: Delete S3 Bucket
        run: |
          aws s3api delete-bucket --bucket terraform-remote-state-ec2-test --region eu-central-1
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

